version: '3'
services:
  shadowsocks-libev:
    image: shadowsocks/shadowsocks-libev:latest
    container_name: shadowsocks-server
    ports:
      - '8388:8388'
      - '8388:8388/udp'
    restart: unless-stopped
    environment:
      PASSWORD: my_password
