version: '3'

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 8080:80
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_password
